name: ci
on: [pull_request_target]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: greet
        uses: ./.github/actions/greet
        with:
          title: ${{ github.event.pull_request.title }}
          mode: release
